apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vote-app-api-repository
  namespace: flux-system
spec:
  interval: 1m
  secretRef:
    name: git-credentials
  ref:
    branch: feature-flux-cd
  url: https://josephassiga@dev.azure.com/josephassiga/migration-factory/_git/pipelines-vote-api
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote-app-api-dev
  namespace: flux-system
spec:
  timeout: 2m
  interval: 5m
  path: ./deploy/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: vote-app-api-repository
  wait: true